services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-reservation_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-reservation_password}
      POSTGRES_DB: ${DB_NAME:-reservation_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-reservation_user} -d ${DB_NAME:-reservation_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${DB_USER:-reservation_user}:${DB_PASSWORD:-reservation_password}@postgres:5432/${DB_NAME:-reservation_db}
      SERVER_ADDR: 0.0.0.0:50051
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
